# base theme (light, dark, intellij, darcula, maclight or macdark); only used by theme editor
@baseTheme = darcula

# Palette
@eigengrau = #16161d
@vanwo = #161932
@oftani = #1b2157
@saron = #2d336b
@keuni = #6e75b3
@bankya = #e5e7ff

eigengrau.color = @eigengrau
vanwo.color = @vanwo
oftani.color = @oftani
saron.color = @saron
keuni.color = @keuni
bankya.color = @bankya

# Background
@background = @eigengrau
TextField.background = @saron
PasswordField.background = @saron


# Foreground
@foreground = @bankya

# Button
@buttonBackground = @keuni
@buttonForeground = @bankya
@buttonHoverBackground = @saron
@buttonPressedBackground = @oftani
@buttonDisabledBackground = @vanwo
@buttonBorderRadius = 16

# Round da thing!
Button.arc = 100
Component.arc = 100
ProgressBar.arc = 100
TextComponent.arc = 100
TextArea.border = 100

# Checkbox & Radio
@checkboxBackground = @vanwo
@checkboxSelectedBackground = @keuni
@checkboxBorder = @saron
@checkboxCheck = @bankya

@radioBackground = @vanwo
@radioSelectedBackground = @keuni
@radioBorder = @saron
@radioDot = @bankya

# Menu & Toolbar
@menuBackground = @oftani
@menuForeground = @bankya
@toolbarBackground = @saron

# Fonts (falta terminar)
@fontPrimary = Sansation
@fontSecondary = Readex Pro
@fontThird = Manjari

# Ejemplo de uso en FlatLaf:
font.family = @fontPrimary
font.family.secondary = @fontSecondary
font.family.third = @fontThird

# Misc
@accentBaseColor = @saron
@borderColor = @saron
@inputBackground = @vanwo
@inputForeground = @bankya
@inputBorder = @keuni
@sliderTrack = @keuni
@sliderThumb = @bankya